push:
  branches:
   - main
pull_request:
  branches:


jobs:
    build:
        name: Azure Pipeline
        runs-on: ubuntu-latest
        steps: 
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/tema-terraform-on-azure-prep/Agile
            azure-pipeline-name: 'Agile-ASP.NET Core (.NET Framework)-CI'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
